"use client";

import { ArrowDown, ArrowRight, ArrowUp, Banknote, Bell, CalendarDays, CheckCircle2, ChevronDown, CircleDollarSign, Download, FileText, Landmark, MoreHorizontal, Plus, ReceiptText, Search, TrendingUp, WalletCards, X } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";

type Stat = { title: string; value: string; note: string; iconKey: "income" | "expense" | "profit" | "due"; trend: "up" | "down" | "flat" };
type Activity = { account: string; amount: string; status: string; statusClass: string; date: string; age: string };
type DistributionSlice = { name: string; value: number; color: string };
type OutstandingInvoice = { client: string; number: string; issue: string; due: string; amount: string; status: string };
type LoanSummary = { balance: string; monthlyEmi: string; activeCount: number; nextDate: string | null };

const STAT_ICON = { income: WalletCards, expense: ReceiptText, profit: TrendingUp, due: Banknote } as const;
const STAT_TONE = { income: "bg-blue-50 text-blue-600", expense: "bg-emerald-50 text-emerald-600", profit: "bg-violet-50 text-violet-600", due: "bg-amber-50 text-amber-600" } as const;
const STAT_DOT = { income: "bg-blue-500", expense: "bg-emerald-500", profit: "bg-violet-500", due: "bg-amber-400" } as const;
const INVOICE_STATUS_TONE: Record<string, string> = { Draft: "bg-slate-100 text-slate-600", Sent: "bg-blue-50 text-blue-600", Overdue: "bg-rose-50 text-rose-600" };

const TRANSACTION_TYPES = [
  { key: "income", label: "Income", description: "Record a payment received from a client or another source.", href: "/income?new=1", icon: WalletCards, gradient: "from-blue-600 to-cyan-500", ring: "hover:border-blue-300 hover:shadow-blue-100" },
  { key: "expense", label: "Expense", description: "Log a business cost, vendor payment, or purchase.", href: "/expenses?new=1", icon: ReceiptText, gradient: "from-rose-600 to-orange-500", ring: "hover:border-rose-300 hover:shadow-rose-100" },
  { key: "salary", label: "Salary", description: "Add a payroll entry for an employee this month.", href: "/salaries?new=1", icon: Banknote, gradient: "from-teal-600 to-emerald-500", ring: "hover:border-teal-300 hover:shadow-teal-100" },
] as const;

export function DashboardOverview({ stats, recentActivity, distribution, outstandingInvoices, greeting, todayLabel, loanSummary }: { stats: Stat[]; recentActivity: Activity[]; distribution: DistributionSlice[]; outstandingInvoices: OutstandingInvoice[]; greeting: string; todayLabel: string; loanSummary: LoanSummary }) {
  const [newTransactionOpen, setNewTransactionOpen] = useState(false);
  const [activitySearch, setActivitySearch] = useState("");
  const filteredActivity = recentActivity.filter((row) => `${row.account} ${row.status}`.toLowerCase().includes(activitySearch.trim().toLowerCase()));
  return <div className="min-h-full text-slate-700">
    <header className="flex flex-col gap-4 border-b border-slate-200 bg-white px-4 py-4 sm:px-5 lg:flex-row lg:items-center lg:justify-between">
      <div><p className="text-[12px] font-medium text-slate-400">Workspace / Overview</p><h1 className="mt-1 text-lg font-semibold tracking-tight text-slate-900">Accounting Dashboard</h1></div>
      <div className="flex flex-wrap items-center gap-2">
        <button className="relative grid size-9 shrink-0 place-items-center rounded-lg border border-slate-200 bg-white text-slate-500"><Bell size={15} /><span className="absolute right-2 top-1.5 size-1.5 rounded-full bg-rose-500 ring-2 ring-white" /></button>
        <span className="relative flex h-9 shrink-0 items-center gap-2 overflow-hidden rounded-lg bg-gradient-to-r from-blue-600 to-violet-600 px-3 text-[12px] font-semibold text-white shadow-md shadow-blue-200"><span className="pointer-events-none absolute -right-3 -top-4 size-10 rounded-full bg-white/15 blur-md" /><span className="relative flex size-1.5"><span className="absolute inline-flex size-full animate-ping rounded-full bg-white/70" /><span className="relative inline-flex size-1.5 rounded-full bg-white" /></span><CalendarDays size={14} className="relative text-white/90" /><span className="relative">{todayLabel}</span></span>
      </div>
    </header>

    <main className="space-y-4 p-3 sm:p-4 lg:p-5">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-base font-semibold text-slate-900">{greeting}</h2><p className="mt-0.5 text-[12px] text-slate-400">Today is {todayLabel} — here is your financial performance and activity.</p></div><div className="flex flex-wrap gap-2"><button onClick={() => setNewTransactionOpen(true)} className="flex h-9 flex-1 items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-[12px] font-semibold sm:flex-none"><Plus size={14} />New transaction</button><button className="flex h-9 flex-1 items-center justify-center gap-2 rounded-lg bg-blue-600 px-3 text-[12px] font-semibold text-white shadow-sm shadow-blue-200 sm:flex-none"><Download size={14} />Export<ChevronDown size={12} /></button></div></div>

      <section className="grid grid-cols-2 gap-3 xl:grid-cols-4">{stats.map((stat) => { const Icon = STAT_ICON[stat.iconKey]; return <article key={stat.title} className="rounded-xl border border-slate-200 bg-white p-3 shadow-[0_2px_12px_rgba(15,23,42,0.025)] transition hover:border-blue-200 hover:shadow-sm sm:p-4"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate text-[11px] font-medium text-slate-400">{stat.title}</p><p className="mt-2 truncate text-base font-semibold tracking-tight text-slate-900 sm:text-xl">{stat.value}</p></div><div className={`grid size-8 shrink-0 place-items-center rounded-full sm:size-9 ${STAT_TONE[stat.iconKey]}`}><Icon size={15} /></div></div><div className="mt-3 flex items-center gap-1.5"><span className={`size-1.5 rounded-full ${STAT_DOT[stat.iconKey]}`} />{stat.trend === "up" && <ArrowUp size={10} className="text-emerald-500" />}{stat.trend === "down" && <ArrowDown size={10} className="text-rose-500" />}<p className="text-[10px] text-slate-400">{stat.note}</p></div></article>; })}</section>

      <section className="grid gap-4 xl:grid-cols-[1.65fr_0.75fr]">
        <article className="overflow-hidden rounded-xl border border-slate-200 bg-white">
          <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 px-4 py-3"><div className="flex items-center gap-2"><div className="grid size-7 shrink-0 place-items-center rounded-lg bg-blue-50 text-blue-600"><CircleDollarSign size={14} /></div><div><h3 className="text-[13px] font-semibold text-slate-900">Financial activity overview</h3><p className="text-[10px] text-slate-400">Most recent income and expense entries</p></div></div><div className="flex gap-2"><label className="hidden h-7 items-center gap-1.5 rounded-md border border-slate-200 px-2 text-slate-400 sm:flex"><Search size={11} /><input value={activitySearch} onChange={(event) => setActivitySearch(event.target.value)} aria-label="Search financial activity" placeholder="Search type..." className="w-24 bg-transparent text-[10px] text-slate-700 outline-none" /></label><Link href="/reports" className="flex h-7 shrink-0 items-center gap-1 rounded-md border border-slate-200 px-2 text-[10px] font-medium text-slate-600 transition hover:border-blue-200 hover:bg-blue-50 hover:text-blue-700">See all<ChevronDown size={10} className="-rotate-90" /></Link></div></div>
          <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead><tr className="border-b border-slate-100 bg-slate-50/50 text-[10px] font-semibold text-slate-400"><th className="px-4 py-2.5">Account</th><th className="px-3 py-2.5">Amount</th><th className="px-3 py-2.5">Status</th><th className="px-3 py-2.5">Date</th><th className="px-3 py-2.5">Age</th></tr></thead><tbody>{filteredActivity.map((row, index) => <tr key={index} className="border-b border-slate-50 text-[11px] transition last:border-0 hover:bg-blue-50/30"><td className="px-4 py-3 font-semibold text-slate-700">{row.account}</td><td className="px-3 py-3 font-semibold text-slate-800">{row.amount}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-[9px] font-semibold ${row.statusClass}`}>{row.status}</span></td><td className="px-3 py-3 text-slate-500">{row.date}</td><td className="px-3 py-3 text-slate-500">{row.age}</td></tr>)}{filteredActivity.length === 0 && <tr><td colSpan={5} className="px-4 py-8 text-center text-[11px] text-slate-400">{recentActivity.length === 0 ? "No transactions recorded yet." : "No activity matches your search."}</td></tr>}</tbody></table></div>
        </article>

        <article className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-[13px] font-semibold text-slate-900">Income vs Expenses</h3><p className="mt-0.5 text-[10px] text-slate-400">Current month</p></div></div>{distribution.length > 0 ? <><div className="mx-auto mt-2 h-56 max-w-60"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={distribution} dataKey="value" innerRadius={54} outerRadius={88} paddingAngle={2} stroke="none">{distribution.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip formatter={(value) => `${value}%`} contentStyle={{ borderRadius: 8, border: "1px solid #e2e8f0", fontSize: 9 }} /></PieChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-x-3 gap-y-2">{distribution.map((item) => <div key={item.name} className="flex items-center gap-1.5"><span className="size-2 rounded-full" style={{ backgroundColor: item.color }} /><p className="flex-1 truncate text-[10px] text-slate-500">{item.name}</p><p className="text-[10px] font-semibold text-slate-700">{item.value}%</p></div>)}</div></> : <div className="grid h-44 place-items-center text-center text-[11px] text-slate-400">No expenses recorded this month.</div>}</article>
      </section>

      <section className="grid gap-4 xl:grid-cols-[1.65fr_0.75fr]">
        <article className="overflow-hidden rounded-xl border border-slate-200 bg-white">
          <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 px-4 py-3"><div className="flex items-center gap-2"><div className="grid size-7 shrink-0 place-items-center rounded-lg bg-violet-50 text-violet-600"><FileText size={14} /></div><div><h3 className="text-[13px] font-semibold text-slate-900">Outstanding invoices</h3><p className="text-[10px] text-slate-400">Invoices requiring attention</p></div></div><div className="flex gap-2"><label className="hidden h-7 items-center gap-1.5 rounded-md border border-slate-200 px-2 text-slate-400 sm:flex"><Search size={11} /><input aria-label="Search invoices" placeholder="Search..." className="w-28 text-[10px] outline-none" /></label><button className="flex h-7 shrink-0 items-center gap-1 rounded-md border border-slate-200 px-2 text-[10px]">Filters<ChevronDown size={10} /></button><button className="grid size-7 shrink-0 place-items-center rounded-md border border-slate-200"><MoreHorizontal size={13} /></button></div></div>
          <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead><tr className="border-b border-slate-100 bg-slate-50/50 text-[10px] font-semibold text-slate-400"><th className="px-4 py-2.5">Client</th><th className="px-3 py-2.5">Invoice</th><th className="px-3 py-2.5">Issue date</th><th className="px-3 py-2.5">Due date</th><th className="px-3 py-2.5">Amount</th><th className="px-3 py-2.5">Status</th></tr></thead><tbody>{outstandingInvoices.map((invoice) => <tr key={invoice.number} className="border-b border-slate-50 text-[11px] last:border-0 hover:bg-slate-50/50"><td className="px-4 py-3 font-semibold text-slate-700">{invoice.client}</td><td className="px-3 py-3 text-blue-600">{invoice.number}</td><td className="px-3 py-3 text-slate-500">{invoice.issue}</td><td className="px-3 py-3 text-slate-500">{invoice.due}</td><td className="px-3 py-3 font-semibold text-slate-800">{invoice.amount}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-[9px] font-semibold ${INVOICE_STATUS_TONE[invoice.status] ?? "bg-slate-100 text-slate-600"}`}>{invoice.status}</span></td></tr>)}{outstandingInvoices.length === 0 && <tr><td colSpan={6} className="px-4 py-8 text-center text-[11px] text-slate-400">No outstanding invoices — you&apos;re all caught up.</td></tr>}</tbody></table></div>
        </article>

        <article className="relative overflow-hidden rounded-xl border border-violet-200 bg-gradient-to-br from-white via-violet-50/60 to-blue-50 p-4 shadow-[0_4px_18px_rgba(99,102,241,0.08)]"><div className="pointer-events-none absolute -right-8 -top-10 size-36 rounded-full bg-violet-200/40 blur-2xl" /><div className="relative flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-violet-100"><Landmark size={16} className="text-violet-600" /></span><div><h3 className="text-[13px] font-semibold text-slate-900">Loans & EMI</h3><p className="text-[10px] text-slate-500">Repayment overview</p></div></div><span className="rounded-full bg-violet-100 px-2.5 py-1 text-[9px] font-semibold text-violet-700">{loanSummary.activeCount} active</span></div>{loanSummary.activeCount > 0 ? <><div className="relative mt-5 rounded-xl border border-violet-100 bg-white/90 p-4"><p className="text-[10px] text-slate-500">Total outstanding balance</p><p className="mt-1 text-xl font-semibold text-slate-900">{loanSummary.balance}</p></div><div className="relative mt-3 grid grid-cols-2 gap-2.5"><div className="rounded-lg border border-amber-100 bg-amber-50 p-3"><p className="text-[9px] text-slate-500">Monthly EMI</p><p className="mt-1 text-[12px] font-semibold text-amber-700">{loanSummary.monthlyEmi}</p></div><div className="rounded-lg border border-blue-100 bg-blue-50 p-3"><p className="text-[9px] text-slate-500">Active loans</p><p className="mt-1 text-[12px] font-semibold text-blue-700">{loanSummary.activeCount}</p></div></div><div className="relative mt-3 flex items-center gap-2 rounded-lg border border-violet-100 bg-white/80 px-3 py-2.5"><CalendarDays size={13} className="text-violet-600" /><div><p className="text-[9px] text-slate-500">Next payment due</p><p className="mt-0.5 text-[10px] font-semibold text-slate-800">{loanSummary.nextDate ?? "No date scheduled"}</p></div></div></> : <div className="relative mt-5 grid min-h-44 place-items-center rounded-xl border border-dashed border-violet-200 bg-white/70 text-center"><div><span className="mx-auto grid size-10 place-items-center rounded-full bg-emerald-100 text-emerald-600"><CheckCircle2 size={17} /></span><p className="mt-3 text-[11px] font-semibold text-slate-900">No active loans</p><p className="mt-1 text-[9px] text-slate-500">Add a loan to track balances and EMI payments.</p></div></div>}<a href="/loans" className="relative mt-4 flex items-center justify-center gap-1.5 rounded-lg bg-violet-600 px-3 py-2.5 text-[10px] font-semibold text-white shadow-sm shadow-violet-200 transition hover:bg-violet-700">Manage loans & EMI<ArrowRight size={12} /></a></article>
      </section>
    </main>

    {newTransactionOpen && <div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/50 p-4 backdrop-blur-sm" onMouseDown={(event) => { if (event.target === event.currentTarget) setNewTransactionOpen(false); }}>
      <div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl">
        <div className="flex items-start justify-between">
          <div><p className="text-[10px] font-semibold uppercase tracking-wider text-blue-600">Quick add</p><h2 className="mt-1 text-xl font-semibold text-slate-900">New transaction</h2><p className="mt-1 text-[11px] text-slate-400">Choose what you&apos;d like to record.</p></div>
          <button onClick={() => setNewTransactionOpen(false)} aria-label="Close" className="grid size-8 place-items-center rounded-lg bg-slate-50 text-slate-500 hover:bg-slate-100"><X size={15} /></button>
        </div>
        <div className="mt-5 space-y-2.5">
          {TRANSACTION_TYPES.map((type) => { const Icon = type.icon; return (
            <a key={type.key} href={type.href} onClick={() => setNewTransactionOpen(false)} className={`group flex items-center gap-3 rounded-2xl border border-slate-200 p-3.5 transition hover:-translate-y-0.5 hover:shadow-lg ${type.ring}`}>
              <span className={`grid size-11 shrink-0 place-items-center rounded-xl bg-gradient-to-br text-white shadow-md ${type.gradient}`}><Icon size={19} /></span>
              <span className="min-w-0 flex-1"><span className="block text-[13px] font-semibold text-slate-900">{type.label}</span><span className="mt-0.5 block text-[10px] leading-4 text-slate-400">{type.description}</span></span>
              <ArrowRight size={15} className="shrink-0 text-slate-300 transition group-hover:translate-x-0.5 group-hover:text-slate-500" />
            </a>
          ); })}
        </div>
      </div>
    </div>}
  </div>;
}
