"use client";

import { useEffect, useState } from "react";
import { Check, Contrast, Eye, Laptop, LayoutPanelLeft, Maximize2, Minimize2, Moon, MousePointer2, Palette, RotateCcw, SlidersHorizontal, Sparkles, Sun, Type, WandSparkles } from "lucide-react";

const accents = [
  { id: "violet", label: "Violet", color: "bg-violet-600", soft: "bg-violet-100" },
  { id: "blue", label: "Ocean", color: "bg-blue-600", soft: "bg-blue-100" },
  { id: "emerald", label: "Emerald", color: "bg-emerald-600", soft: "bg-emerald-100" },
  { id: "rose", label: "Rose", color: "bg-rose-600", soft: "bg-rose-100" },
  { id: "amber", label: "Amber", color: "bg-amber-500", soft: "bg-amber-100" },
  { id: "navy", label: "Navy", color: "bg-[#061d40]", soft: "bg-slate-200" },
];
type Mode = "light" | "dark" | "system";

export function PersonalizationPage() {
  const [mode, setMode] = useState<Mode>("light");
  const [accent, setAccent] = useState("violet");
  const [density, setDensity] = useState("comfortable");
  const [fontSize, setFontSize] = useState("default");
  const [motion, setMotion] = useState("full");
  const [sidebar, setSidebar] = useState("expanded");
  const [highContrast, setHighContrast] = useState(false);
  const [saved, setSaved] = useState(false);

  useEffect(() => { const timer = window.setTimeout(() => { setMode((localStorage.getItem("akcounting-theme") ?? "light") as Mode); setAccent(localStorage.getItem("akcounting-accent") ?? "violet"); setDensity(localStorage.getItem("akcounting-density") ?? "comfortable"); setFontSize(localStorage.getItem("akcounting-font-size") ?? "default"); setMotion(localStorage.getItem("akcounting-motion") ?? "full"); setSidebar(localStorage.getItem("akcounting-sidebar") ?? "expanded"); setHighContrast(localStorage.getItem("akcounting-contrast") === "true"); }, 0); return () => window.clearTimeout(timer); }, []);

  function updateMode(value: Mode) { setMode(value); localStorage.setItem("akcounting-theme", value); const resolved = value === "system" ? (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light") : value; document.documentElement.dataset.theme = resolved; document.documentElement.dataset.themePreference = value; }
  function updateAccent(value: string) { setAccent(value); localStorage.setItem("akcounting-accent", value); document.documentElement.dataset.accent = value; }
  function updateSetting(key: string, value: string, setter: (value: string) => void) { setter(value); localStorage.setItem(key, value); const datasetKey = key.replace("akcounting-", "").replace(/-([a-z])/g, (_, letter) => letter.toUpperCase()); document.documentElement.dataset[datasetKey] = value; }
  function reset() { updateMode("light"); updateAccent("violet"); updateSetting("akcounting-density", "comfortable", setDensity); updateSetting("akcounting-font-size", "default", setFontSize); updateSetting("akcounting-motion", "full", setMotion); setSidebar("expanded"); localStorage.setItem("akcounting-sidebar", "expanded"); setHighContrast(false); localStorage.setItem("akcounting-contrast", "false"); document.documentElement.dataset.contrast = "false"; }
  function save() { setSaved(true); window.setTimeout(() => setSaved(false), 1800); }

  return <div className="personalization-page mx-auto max-w-6xl">
    <header className="flex flex-col gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[9px] font-semibold uppercase tracking-[0.18em] text-violet-600">Workspace preferences</p><h1 className="mt-1.5 text-2xl font-semibold tracking-tight text-slate-950">Personalization</h1><p className="mt-1 text-[10px] text-slate-500">Make AKCounting feel comfortable, focused, and uniquely yours.</p></div><div className="flex gap-2"><button onClick={reset} className="flex h-9 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-[9px] font-semibold text-slate-600"><RotateCcw size={12} />Reset defaults</button><button onClick={save} className="flex h-9 items-center gap-2 rounded-lg bg-violet-600 px-4 text-[9px] font-semibold text-white">{saved ? <Check size={12} /> : <Sparkles size={12} />}{saved ? "Preferences saved" : "Save changes"}</button></div></header>

    <section className="mt-5 grid gap-4 xl:grid-cols-[1fr_340px]"><div className="space-y-4">
      <article className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-violet-50 text-violet-700"><Sun size={17} /></span><div><h2 className="text-sm font-semibold text-slate-900">Appearance mode</h2><p className="mt-1 text-[8px] text-slate-400">Choose how AKCounting looks across every page.</p></div></div><div className="mt-5 grid grid-cols-3 gap-3">{([{ id: "light", label: "Light", icon: Sun, body: "bg-slate-50", panel: "bg-white" }, { id: "dark", label: "Dark", icon: Moon, body: "bg-slate-900", panel: "bg-slate-700" }, { id: "system", label: "System", icon: Laptop, body: "bg-gradient-to-r from-slate-50 to-slate-900", panel: "bg-white" }] as const).map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => updateMode(item.id)} className={`rounded-xl border p-2 text-left transition ${mode === item.id ? "border-violet-500 ring-2 ring-violet-50" : "border-slate-200 hover:border-violet-200"}`}><div className={`h-20 overflow-hidden rounded-lg p-2 ${item.body}`}><div className={`h-full rounded-md p-2 shadow-sm ${item.panel}`}><div className="h-1.5 w-8 rounded-full bg-violet-400" /><div className="mt-2 h-1 w-full rounded-full bg-slate-200" /><div className="mt-1 h-1 w-2/3 rounded-full bg-slate-200" /></div></div><div className="mt-2 flex items-center gap-1.5"><Icon size={12} className={mode === item.id ? "text-violet-600" : "text-slate-400"} /><p className={`text-[8px] font-semibold ${mode === item.id ? "text-violet-700" : "text-slate-600"}`}>{item.label}</p>{mode === item.id && <Check size={11} className="ml-auto text-violet-600" />}</div></button>; })}</div></article>

      <article className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-violet-50 text-violet-700"><Palette size={17} /></span><div><h2 className="text-sm font-semibold text-slate-900">Accent color</h2><p className="mt-1 text-[8px] text-slate-400">Used for active navigation, primary buttons, and highlights.</p></div></div><div className="mt-5 grid grid-cols-3 gap-2 sm:grid-cols-6">{accents.map((item) => <button key={item.id} onClick={() => updateAccent(item.id)} className={`rounded-xl border p-2.5 text-center transition ${accent === item.id ? "border-slate-400 bg-slate-50" : "border-slate-100 hover:border-slate-200"}`}><span className={`mx-auto grid size-9 place-items-center rounded-full ${item.soft}`}><i className={`size-5 rounded-full ${item.color}`} />{accent === item.id && <Check size={10} className="absolute text-white" />}</span><p className="mt-2 text-[8px] font-medium text-slate-600">{item.label}</p></button>)}</div></article>

      <article className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><SlidersHorizontal size={17} /></span><div><h2 className="text-sm font-semibold text-slate-900">Interface & layout</h2><p className="mt-1 text-[8px] text-slate-400">Control spacing, sizing, and navigation behavior.</p></div></div><div className="mt-5 divide-y divide-slate-100">
        <SettingRow icon={Maximize2} title="Interface density" description="Adjust spacing between cards, tables, and controls"><Segment value={density} onChange={(value) => updateSetting("akcounting-density", value, setDensity)} options={[{ id: "compact", label: "Compact" }, { id: "comfortable", label: "Comfortable" }]} /></SettingRow>
        <SettingRow icon={Type} title="Text size" description="Change the overall interface scale"><Segment value={fontSize} onChange={(value) => updateSetting("akcounting-font-size", value, setFontSize)} options={[{ id: "small", label: "Small" }, { id: "default", label: "Default" }, { id: "large", label: "Large" }]} /></SettingRow>
        <SettingRow icon={LayoutPanelLeft} title="Sidebar on startup" description="Choose how the sidebar opens"><Segment value={sidebar} onChange={(value) => { setSidebar(value); localStorage.setItem("akcounting-sidebar", value); }} options={[{ id: "expanded", label: "Expanded" }, { id: "collapsed", label: "Collapsed" }]} /></SettingRow>
      </div></article>

      <article className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Eye size={17} /></span><div><h2 className="text-sm font-semibold text-slate-900">Accessibility</h2><p className="mt-1 text-[8px] text-slate-400">Fine-tune visual comfort and animation.</p></div></div><div className="mt-5 divide-y divide-slate-100"><SettingRow icon={MousePointer2} title="Motion" description="Reduce animation and transition effects"><Segment value={motion} onChange={(value) => updateSetting("akcounting-motion", value, setMotion)} options={[{ id: "full", label: "Full" }, { id: "reduced", label: "Reduced" }]} /></SettingRow><SettingRow icon={Contrast} title="High contrast" description="Increase borders and text contrast"><Toggle checked={highContrast} onChange={() => { const value = !highContrast; setHighContrast(value); localStorage.setItem("akcounting-contrast", String(value)); document.documentElement.dataset.contrast = String(value); }} /></SettingRow></div></article>
    </div>

    <aside className="h-fit xl:sticky xl:top-8"><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold text-slate-900">Live preview</h2><p className="mt-0.5 text-[8px] text-slate-400">Your current appearance</p></div><WandSparkles size={16} className="text-violet-600" /></div><div className={`mt-5 overflow-hidden rounded-xl border border-slate-200 ${mode === "dark" ? "bg-slate-900" : "bg-slate-50"}`}><div className={`flex h-10 items-center gap-2 border-b px-3 ${mode === "dark" ? "border-slate-700 bg-slate-800" : "border-slate-200 bg-white"}`}><span className={`grid size-5 place-items-center rounded ${accents.find((item) => item.id === accent)?.color ?? "bg-violet-600"}`}><Sparkles size={9} className="text-white" /></span><div className={`h-1.5 w-16 rounded-full ${mode === "dark" ? "bg-slate-600" : "bg-slate-200"}`} /></div><div className="grid grid-cols-[50px_1fr]"><div className={`min-h-56 border-r p-2 ${mode === "dark" ? "border-slate-700 bg-slate-800" : "border-slate-200 bg-white"}`}>{[1, 2, 3, 4].map((item) => <div key={item} className={`mb-2 h-5 rounded ${item === 1 ? accents.find((color) => color.id === accent)?.soft : mode === "dark" ? "bg-slate-700" : "bg-slate-100"}`} />)}</div><div className="p-3"><div className={`h-2 w-24 rounded-full ${mode === "dark" ? "bg-slate-600" : "bg-slate-300"}`} /><div className="mt-3 grid grid-cols-2 gap-2">{[1, 2, 3, 4].map((item) => <div key={item} className={`h-12 rounded-lg border ${mode === "dark" ? "border-slate-700 bg-slate-800" : "border-slate-200 bg-white"}`} />)}</div><div className={`mt-2 h-20 rounded-lg border ${mode === "dark" ? "border-slate-700 bg-slate-800" : "border-slate-200 bg-white"}`} /></div></div></div><div className="mt-4 rounded-xl bg-violet-50 p-3"><p className="flex items-center gap-2 text-[8px] font-semibold text-violet-700"><WandSparkles size={11} />Changes apply instantly</p><p className="mt-1 text-[7px] leading-4 text-violet-500">Your preferences are saved on this device and restored when you return.</p></div></div>
    </aside></section>
  </div>;
}

function SettingRow({ icon: Icon, title, description, children }: { icon: typeof Minimize2; title: string; description: string; children: React.ReactNode }) { return <div className="flex flex-col gap-3 py-4 first:pt-0 last:pb-0 sm:flex-row sm:items-center"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-slate-50 text-slate-500"><Icon size={14} /></span><div className="flex-1"><p className="text-[9px] font-semibold text-slate-700">{title}</p><p className="mt-0.5 text-[8px] text-slate-400">{description}</p></div>{children}</div>; }
function Segment({ value, onChange, options }: { value: string; onChange: (value: string) => void; options: { id: string; label: string }[] }) { return <div className="flex rounded-lg bg-slate-100 p-1">{options.map((option) => <button key={option.id} onClick={() => onChange(option.id)} className={`h-7 rounded-md px-2.5 text-[8px] font-semibold ${value === option.id ? "bg-white text-slate-800 shadow-sm" : "text-slate-400"}`}>{option.label}</button>)}</div>; }
function Toggle({ checked, onChange }: { checked: boolean; onChange: () => void }) { return <button onClick={onChange} className={`relative h-6 w-11 rounded-full transition ${checked ? "bg-violet-600" : "bg-slate-200"}`}><span className={`absolute top-1 size-4 rounded-full bg-white shadow transition ${checked ? "left-6" : "left-1"}`} /></button>; }
