"use client";

import { ArrowUpRight, CalendarDays, Check, Clock3, CreditCard, Download, FileText, Sparkles, Users, WalletCards, X } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

import type { MySubscriptionOverview } from "@/actions/subscription";

const money = (value: number) => `Rs ${new Intl.NumberFormat("en-NP", { maximumFractionDigits: 0 }).format(value)}`;
const STATUS_TONE = { Active: "bg-emerald-400/15 text-emerald-300", Trial: "bg-blue-400/15 text-blue-300", Expired: "bg-rose-400/15 text-rose-300" } as const;
const PAYMENT_STATUS_TONE: Record<string, string> = { Complete: "bg-emerald-50 text-emerald-700", Pending: "bg-amber-50 text-amber-700", Failed: "bg-rose-50 text-rose-700" };

export function SettingsSubscription({ overview }: { overview: MySubscriptionOverview }) {
  const [notice, setNotice] = useState("");
  function download(invoice: string) { setNotice(`${invoice} receipt downloaded`); window.setTimeout(() => setNotice(""), 1800); }

  const planLabel = overview.plan.replace(" Package", "");

  return <section className="mt-4 space-y-4">
    <article className="relative overflow-hidden rounded-2xl bg-[#081b3a] p-6 text-white shadow-xl shadow-slate-200"><div className="absolute -right-20 -top-24 size-64 rounded-full bg-violet-500/25 blur-3xl" /><div className="relative grid gap-6 lg:grid-cols-[1fr_360px] lg:items-center"><div><span className="inline-flex items-center gap-2 rounded-full bg-violet-400/15 px-3 py-1.5 text-[8px] font-semibold text-violet-200"><Sparkles size={11} />CURRENT SUBSCRIPTION</span><div className="mt-4 flex items-end gap-3"><h2 className="text-3xl font-semibold tracking-tight">AKCounting {planLabel}</h2><span className={`mb-1 rounded-full px-2.5 py-1 text-[8px] font-semibold ${STATUS_TONE[overview.status]}`}>{overview.status}</span></div><p className="mt-2 max-w-lg text-[10px] leading-5 text-slate-300">{overview.plan === "Premium Package" ? "Unlimited accounting tools, advanced reports, invoices, documents, and collaboration for your growing business." : overview.plan === "Growth Package" ? "Grow your workspace with more team seats, document storage, and image uploads." : "The essentials to get your accounting workspace running."}</p><div className="mt-5 flex flex-wrap gap-2"><Link href="/subscription" className="flex h-10 items-center gap-2 rounded-xl bg-violet-500 px-4 text-[9px] font-semibold text-white">Change plan <ArrowUpRight size={13} /></Link><Link href="/subscription" className="flex h-10 items-center rounded-xl border border-white/15 px-4 text-[9px] font-semibold text-slate-200">Manage billing</Link></div></div><div className="rounded-2xl border border-white/10 bg-white/[0.07] p-5 backdrop-blur"><div className="flex items-center justify-between"><div><p className="text-[8px] text-slate-400">Next payment</p><p className="mt-1 text-xl font-semibold">{money(overview.planPrice)}</p></div><span className="grid size-10 place-items-center rounded-xl bg-white/10 text-violet-300"><CalendarDays size={17} /></span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-fuchsia-400" style={{ width: `${overview.percentElapsed}%` }} /></div><div className="mt-3 flex items-center justify-between"><p className="text-[8px] text-slate-400">{overview.planRenewsAtLabel ? `Renews ${overview.planRenewsAtLabel}` : "No active renewal date"}</p><p className="text-[9px] font-semibold text-violet-200">{overview.status === "Expired" ? "Expired" : `${overview.daysLeft} day${overview.daysLeft === 1 ? "" : "s"} left`}</p></div><div className="mt-4 flex items-center gap-2 border-t border-white/10 pt-4"><CreditCard size={13} className="text-slate-400" /><p className="text-[8px] text-slate-300">Paid via eSewa</p></div></div></div></article>

    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <article className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-600"><WalletCards size={16} /></span><div><p className="text-[8px] text-slate-400">Billing cycle</p><p className="mt-1 text-[11px] font-semibold text-slate-800">Monthly</p><p className="mt-0.5 text-[7px] text-slate-400">Renews automatically</p></div></article>
      <article className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-600"><CalendarDays size={16} /></span><div><p className="text-[8px] text-slate-400">Member since</p><p className="mt-1 text-[11px] font-semibold text-slate-800">{overview.memberSince}</p><p className="mt-0.5 text-[7px] text-slate-400">{overview.successfulPayments} successful payment{overview.successfulPayments === 1 ? "" : "s"}</p></div></article>
      <article className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-600"><Users size={16} /></span><div><p className="text-[8px] text-slate-400">Team seats</p><p className="mt-1 text-[11px] font-semibold text-slate-800">{overview.teamSeatsUsed} of {overview.teamSeatsLimit}</p><p className="mt-0.5 text-[7px] text-slate-400">{Math.max(0, overview.teamSeatsLimit - overview.teamSeatsUsed)} seat{overview.teamSeatsLimit - overview.teamSeatsUsed === 1 ? "" : "s"} available</p></div></article>
      <article className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-600"><FileText size={16} /></span><div><p className="text-[8px] text-slate-400">Documents</p><p className="mt-1 text-[11px] font-semibold text-slate-800">{overview.documentsUsed} of {overview.documentsLimit}</p><p className="mt-0.5 text-[7px] text-slate-400">{overview.documentsLimit === 0 ? "Uploads locked on this plan" : `${Math.max(0, overview.documentsLimit - overview.documentsUsed)} remaining`}</p></div></article>
    </div>

    <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-semibold text-slate-900">Payment history</h2><p className="mt-1 text-[8px] text-slate-400">Previous subscription payments and downloadable receipts</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead><tr className="bg-slate-50 text-[8px] font-semibold uppercase tracking-wider text-slate-400"><th className="px-5 py-3">Invoice</th><th className="px-5 py-3">Payment date</th><th className="px-5 py-3">Plan</th><th className="px-5 py-3">Source</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Receipt</th></tr></thead><tbody>{overview.payments.map((payment) => <tr key={payment.id} className="border-t border-slate-100 text-[9px] text-slate-600 hover:bg-slate-50/70"><td className="px-5 py-4 font-semibold text-slate-800">{payment.invoice}</td><td className="px-5 py-4">{payment.date}</td><td className="px-5 py-4">{payment.plan.replace(" Package", "")}</td><td className="px-5 py-4">{payment.method}</td><td className="px-5 py-4 font-semibold text-slate-800">{money(payment.amount)}</td><td className="px-5 py-4"><span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[7px] font-semibold ${PAYMENT_STATUS_TONE[payment.status] ?? "bg-slate-100 text-slate-600"}`}>{payment.status === "Complete" ? <Check size={9} /> : payment.status === "Pending" ? <Clock3 size={9} /> : <X size={9} />}{payment.status}</span></td><td className="px-5 py-4 text-right">{payment.status === "Complete" ? <button onClick={() => download(payment.invoice)} aria-label={`Download ${payment.invoice}`} className="grid size-8 place-items-center rounded-lg bg-slate-50 text-slate-500 hover:bg-violet-50 hover:text-violet-600"><Download size={13} /></button> : <span className="text-[8px] text-slate-300">—</span>}</td></tr>)}</tbody></table></div>
      {overview.payments.length === 0 && <div className="p-8 text-center text-[10px] text-slate-400">No payments yet — your subscription is still on a free trial.</div>}
    </article>
    {overview.extensions.length > 0 && <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex items-center gap-3 border-b border-slate-100 p-5"><span className="grid size-9 place-items-center rounded-lg bg-emerald-50 text-emerald-600"><Clock3 size={16} /></span><div><h2 className="text-sm font-semibold text-slate-900">Free extension history</h2><p className="mt-0.5 text-[8px] text-slate-400">One-time free extensions used when your subscription ended</p></div></div><div className="divide-y divide-slate-50">{overview.extensions.map((extension) => <div key={extension.id} className="flex items-center justify-between px-5 py-3"><p className="flex items-center gap-2 text-[9px] font-medium text-slate-700"><Sparkles size={12} className="text-emerald-500" />+{extension.days} days added for free</p><div className="text-right"><p className="text-[8px] text-slate-500">Extended {extension.extendedAtLabel ?? extension.extendedAt}</p><p className="mt-0.5 text-[8px] text-slate-400">Ended {extension.endsAtLabel ?? extension.endsAt}</p></div></div>)}</div></article>}

    {notice && <div className="fixed bottom-6 right-6 z-[90] flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-[9px] font-semibold text-white shadow-xl"><Check size={13} className="text-emerald-400" />{notice}</div>}
  </section>;
}
